version: '3.8'
services:
  squid:
    image: gridlastic/docker-squid

  gridc-tunnel-to-squid:
    image: gridlastic/docker-gridc
    volumes:
      - ./custom-config-template.cfg:/home/gridc/config-template.cfg
    environment:
      GRIDC_ENDPOINT_SUBDOMAIN: ${GRIDC_ENDPOINT_SUBDOMAIN}
      GRIDC_USERNAME: ${GRIDC_USERNAME}
      GRIDC_ACCESS_KEY: ${GRIDC_ACCESS_KEY}
      GRIDC_REMOTE_PORT: ${GRIDC_REMOTE_PORT}
      GRIDC_START_CONFIG_TUNNELS: all